### PR TITLE
Fixed totalRails counting error.

### PR DESCRIPTION
**Pull request by dorrzun**
Resolved totalRails count being incredibly wrong. I looked into using the Block class for a rewrite, but it just makes more sense to truncate/normalize the rogue value via the setter.

### CODE REVIEW

**Comment by Geitenijs** [comment]
I've been testing it and the patch doesn't seem to fix the issue.
Track has 43 rails, but it never actually says 43

Have a look: https://postimg.cc/gallery/9QbB4Mf

**Comment by dorrzun** [comment]
Should be all fixed now with the latest commit! There was a missing check in the getNSEW() functions, allowing duplicates. Not sure when that appeared in the source code, but has been there since the beginning.

Let me know if the issues (somehow) still persist!

**Comment by Geitenijs** [comment]
I see!

The count has been fixed and it works great, however the command no longer marks/releases chunks for me.

**Comment by dorrzun** [comment]
Hahaha oh the wonders of debugging! Take a look at the latest commit, it's now working again for me :)

**Comment by Geitenijs** [comment]
It actually finds the right chunks but it somehow doesn't load them...

Screenshot

**Comment by dorrzun** [comment]
Uh oh! I’m not sure where the issue might be for that...where to start?

**Comment by Geitenijs** [comment]
Not sure, don't have time to really look into it at the moment. Will do soon. If you find anything, please let me know!

**Comment by dorrzun** [comment]
Of course! If there are any crash course tips for debugging this issue, let me know. I’ll work on this today and see where I get!

**Comment by dorrzun** [comment]
Screenshot from 2020-05-27 17-39-28

Looks like chunks are staying force loaded for some reason. It's at least a clue!

**Comment by Geitenijs** [comment]
Oh wow!
When I saw the notification email for your initial comment, I quickly reviewed the code and figured that had to be the issue. Thank you for looking into it as well, really appreciate your work!

Will address tomorrow, just need to figure out how to properly sync the forceload & KC list

**Pull request closed without merging**
